services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_api
    ports:
      - "8000:8000"
    environment: 
      MYSQL_HOST: mysql
      MONGO_HOST: mongo
      GRPC_HOST: grpc
      GRPC_PORT: 50051
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: event_manager
      MONGO_URL: mongodb://mongo:27017/
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
      grpc:
        condition: service_started 
    networks:
      - appnet

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27018:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: event_manager
    ports:
      - "3307:3306"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 

  client_service: 
    build:
      context: ./client_service 
      dockerfile: Dockerfile
    container_name: client_api
    ports:
      - "8001:8001" 
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      MONGO_HOST: mongo
      MYSQL_HOST: mysql 
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: event_manager
    networks:
      - appnet

  grpc:
    build: ./app
    container_name: grpc_server
    ports:
      - "50051:50051"
    networks:
      - appnet

  frontend:
    build: ./frontend 
    ports:
      - "5173:5173"
    stdin_open: true 
    tty: true
    depends_on:
      - api

networks:
  appnet: